version: "3.3"

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - zitadel
  graphql:
    build:
      context: ./backend
      dockerfile: dev.dockerfile
    container_name: graphql
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
    ports:
      - ${BACKEND_PORT}:8443
    env_file:
      - .env
    depends_on:
      - mongodb
    networks: 
      - zitadel
  admin:
    build:
      context: ./frontend
      dockerfile: dev.dockerfile
    container_name: admin
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
     volumes:
      - /app/node_modules
      - ./frontend/:/app
    ports:
      - 80:3000
    env_file:
      - .env
    depends_on:
      - graphql
      - mongodb
      - zinc
    networks: 
      - zitadel
  zinc:
    image: public.ecr.aws/h9e2j3o7/zinc:latest
    restart: unless-stopped
    container_name: zinc
    volumes:
      - ./zinc:/data
    ports:
      - 4080:4080
    depends_on:
      - graphql
      - mongodb
    env_file:
      - .env
  zitadel:
    container_name: auth
    restart: unless-stopped
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:v2.0.0-v2-alpha.33-amd64'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_HOST=db'
      - 'ZITADEL_EXTERNALSECURE=false'
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    container_name: auth-db
    restart: unless-stopped
    networks:
      - 'zitadel'
    image: 'cockroachdb/cockroach:v22.1.0'
    command: 'start-single-node --insecure'
    ports:
      - 9090:8080
      - 26257:26257
    networks: 
      - zitadel
    volumes:
      - ./auth_db:/cockroach/cockroach-data"

volumes:
  mongo:
networks:
  zitadel:
  
