version: "3"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./mongo:/data/db
  graphql:
    build:
      context: ./backend
      dockerfile: dev.dockerfile
    container_name: graphql
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
    ports:
      - ${BACKEND_PORT}:8443
    env_file:
      - .env
    depends_on:
      - mongo
    networks: 
      - zitadel
  admin:
    build:
      context: ./frontend
      dockerfile: dev.dockerfile
    container_name: admin
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped
    ports:
      - 4000:3000
    volumes:
      - /app/node_modules
      - ./frontend/:/home/app/admin-tool
    env_file:
      - .env
    depends_on:
      - graphql
      - mongo
      - zinc
    networks: 
      - zitadel
  zinc:
    image: public.ecr.aws/h9e2j3o7/zinc:latest
    container_name: zinc
    volumes:
      - ./zinc:/data
    ports:
      - 4080:4080
    depends_on:
      - graphql
      - mongo
    env_file:
      - .env
  zitadel:
    container_name: auth
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:v2.0.0-v2-alpha.33-amd64'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_HOST=db'
      - 'ZITADEL_EXTERNALSECURE=false'
    depends_on:
      db:
        condition: 'service_healthy'
    ports:
      - 8080:8080

  db:
    container_name: auth-db
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'cockroachdb/cockroach:v22.1.0'
    command: 'start-single-node --insecure'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - 9090:8080
      - 26257:26257
    networks: 
      - zitadel
    volumes:
      - ./auth_db:/cockroach/cockroach-data"
volumes:
  mongo_storage:
  
networks:
  zitadel:
