version: "3.3"

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - zitadel
  graphql:
    build:
      context: ./backend
      dockerfile: production.dockerfile
    container_name: graphql
    restart: unless-stopped
    ports:
      - ${BACKEND_PORT}:8443
    env_file:
      - .env
    depends_on:
      - mongodb
    networks: 
      - zitadel
  admin:
    build:
      context: ./frontend
      dockerfile: production.dockerfile
    container_name: admin
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - graphql
      - mongodb
      - zinc
    networks: 
      - zitadel
  zinc:
    image: public.ecr.aws/h9e2j3o7/zinc:latest
    restart: unless-stopped
    container_name: zinc
    volumes:
      - ./zinc:/data
    ports:
      - 4080:4080
    depends_on:
      - graphql
      - mongodb
    env_file:
      - .env
    networks:
      - zitadel
  # keploy:
  #   image: ghcr.io/keploy/keploy
  #   ports:
  #     - 8081:8081
  #   environment:
  #     KEPLOY_MODE: "off"
  #     KEPLOY_MONGO_URI: "mongodb://mongo:27017"
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - zitadel


volumes:
  mongo:
networks:
  zitadel:
  
