version: "3.3"

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - cms-network
  graphql:
    build:
      context: ./backend
      dockerfile: production.dockerfile
    container_name: graphql
    restart: unless-stopped
    ports:
      - "8443:8443"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks: 
      - cms-network
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.dockerfile
    container_name: admin
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - graphql
      - mongodb
      - zinc
    env_file:
      - .env
    networks: 
      - cms-network
  zinc:
    image: public.ecr.aws/h9e2j3o7/zinc:latest
    restart: unless-stopped
    container_name: zinc
    volumes:
      - zinc:/data
    ports:
      - 4080:4080
    depends_on:
      - graphql
      - mongodb
    env_file:
      - .env
    networks:
      - cms-network
  redis:
    image: redis
    restart: unless-stopped
    container_name: redis
    volumes:
      - cache:/data
    ports:
      - 6379:6379
    depends_on:
      - graphql
      - mongodb
      - zinc
    networks:
      - cms-network
    

volumes:
  mongo:
  zinc:
  cache:
networks:
  cms-network:
  
