# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/v2-alpha/cmd/defaults.yaml

# If not using the docker compose example, adjust these values for connecting ZITADEL to your CockroachDB
Database:
  User:
    # If the user doesn't exist already, it is created
    Username: ${PROD_ZITADEL_DB_USERNAME}
    Password: ${PROD_ZITADEL_DB_USER_PASSWORD}
AdminUser:
  Username: ${PROD_ZITADEL_ADMIN_USERNAME}
  Password: ${PROD_ZITADEL_ADMIN_USER_PASSWORD}
